// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SafeEntry.Infrastructure.Data;

#nullable disable

namespace SafeEntry.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523055118_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SafeEntry.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Persons", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Employee", b =>
                {
                    b.HasBaseType("SafeEntry.Domain.Entities.Person");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Resident", b =>
                {
                    b.HasBaseType("SafeEntry.Domain.Entities.Person");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.HasIndex("AddressId");

                    b.ToTable("Residents", (string)null);
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Visitor", b =>
                {
                    b.HasBaseType("SafeEntry.Domain.Entities.Person");

                    b.ToTable("Visitors", (string)null);
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Employee", b =>
                {
                    b.HasOne("SafeEntry.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("SafeEntry.Domain.Entities.Employee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Resident", b =>
                {
                    b.HasOne("SafeEntry.Domain.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SafeEntry.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("SafeEntry.Domain.Entities.Resident", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("SafeEntry.Domain.Entities.Visitor", b =>
                {
                    b.HasOne("SafeEntry.Domain.Entities.Person", null)
                        .WithOne()
                        .HasForeignKey("SafeEntry.Domain.Entities.Visitor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
